name = "Minimo"
license = "MIT"
licenselink = "https://github.com/numeconcopenhagen/numeconcopenhagentheme/blob/master/LICENSE"
description = "Minimal course theme for Hugo"
homepage = "https://numeconcopenhagen.netlify.com"
tags = [
  "blog",
  "minimal"
]

[author]
  name = "Jakob Jul Elben"
