baseURL: "http://www.example.com"
title: "This is ITPANA"
theme: "NumEconCopenhagenTheme"

menu:
  menu1:
    - name: "Exercises"
      url: "/exercises/"
      weight: 10
    - name: "Lectures"
      url: "/lectures/"
      weight: 20
  menu2:
    - name: "Google"
      url: "https://google.com/"

ignorefiles: []

pygmentsuseclasses: true